const path = require('path');
const fs = require('fs');
const express = require('express');

const config = require('./config');
const { getProjects, getProjectUsers, getProjectClientUsers, getProjectTasks } = require('./zohoClient');
const { sanitizeMomPayload, validateMomPayload } = require('./momTemplate');
const { generateMomPdf } = require('./pdfService');

const app = express();
const DIGITAL_DECLARATION_STATEMENT =
  'This Minutes of Meeting (M.O.M) is a digitally generated record of meeting discussions and outcomes. It is produced from system-captured inputs and therefore does not require a handwritten signature for verification.';

function pad2(value) {
  return String(value).padStart(2, '0');
}

function formatAuthTimestamp(date) {
  const year = date.getFullYear();
  const month = pad2(date.getMonth() + 1);
  const day = pad2(date.getDate());
  const hours = pad2(date.getHours());
  const minutes = pad2(date.getMinutes());
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

function generateDocumentId(date) {
  const year = date.getFullYear();
  const month = pad2(date.getMonth() + 1);
  const day = pad2(date.getDate());
  const hours = pad2(date.getHours());
  const minutes = pad2(date.getMinutes());
  const seconds = pad2(date.getSeconds());
  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  return `M.O.M-${year}${month}${day}-${hours}${minutes}${seconds}-${randomSuffix}`;
}

function buildAuthenticityMetadata() {
  const generatedAtDate = new Date();
  const generatedAt = formatAuthTimestamp(generatedAtDate);
  const documentId = generateDocumentId(generatedAtDate);
  const generatedBy = String(config.app.generatedBy || 'M.O.M System').trim() || 'M.O.M System';
  return {
    statement: DIGITAL_DECLARATION_STATEMENT,
    documentId,
    generatedAt,
    generatedBy,
    line: `Document ID: ${documentId} | Generated: ${generatedAt} | Generated by: ${generatedBy}`
  };
}

if (!fs.existsSync(config.app.generatedDir)) {
  fs.mkdirSync(config.app.generatedDir, { recursive: true });
}

app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ extended: true }));

app.use('/generated-pdfs', express.static(config.app.generatedDir));
app.use(express.static(path.join(config.app.rootDir, 'public')));

function buildAbsolutePdfUrl(pdfUrl) {
  try {
    return new URL(pdfUrl, config.app.baseUrl).toString();
  } catch (_error) {
    return `${String(config.app.baseUrl || '').replace(/\/+$/, '')}${pdfUrl}`;
  }
}

function buildOutlookDraft({ mom, options, pdfUrl }) {
  const to = String(options.emailTo || '').trim();
  const cc = String(options.emailCc || '').trim();
  const subject = String(options.emailSubject || '').trim() || `Minutes of Meeting - ${mom.projectName}`;
  const pdfAbsoluteUrl = buildAbsolutePdfUrl(pdfUrl);

  const defaultBodyLines = [
    'Dear Team,',
    '',
    `Please find the Minutes of Meeting for "${mom.projectName}" below.`,
    `PDF Link: ${pdfAbsoluteUrl}`,
    '',
    'Please attach the generated PDF manually before sending.',
    '',
    'Regards,',
    'M.O.M App'
  ];

  const customBody = String(options.emailBody || '').trim();
  const body = customBody
    ? `${customBody}\n\nPDF Link: ${pdfAbsoluteUrl}\n\nPlease attach the generated PDF manually before sending.`
    : defaultBodyLines.join('\n');

  const outlookQueryParts = [];
  if (to) {
    outlookQueryParts.push(`to=${encodeURIComponent(to)}`);
  }
  if (cc) {
    outlookQueryParts.push(`cc=${encodeURIComponent(cc)}`);
  }
  outlookQueryParts.push(`subject=${encodeURIComponent(subject)}`);
  outlookQueryParts.push(`body=${encodeURIComponent(body)}`);
  const outlookQuery = outlookQueryParts.join('&');

  return {
    mode: 'outlook-draft',
    to,
    cc,
    subject,
    body,
    pdfAbsoluteUrl,
    outlookComposeUrl: `https://outlook.office.com/mail/deeplink/compose?${outlookQuery}`,
    attachmentAutoSupported: false,
    attachmentNote:
      'Attachment cannot be auto-added by browser deeplink. The generated PDF is opened for manual attachment.'
  };
}

app.get('/api/health', (_req, res) => {
  const zohoAutoRefreshConfigured = Boolean(
    config.zoho.refreshToken && config.zoho.clientId && config.zoho.clientSecret
  );

  res.json({
    success: true,
    timestamp: new Date().toISOString(),
    zohoMode: config.zoho.useMock ? 'mock' : 'live',
    zohoAutoRefreshConfigured,
    generatedBy: String(config.app.generatedBy || 'M.O.M System'),
    emailEnabled: true,
    emailMode: 'outlook-draft'
  });
});

app.get('/api/zoho/projects', async (req, res) => {
  try {
    const query = String(req.query.query || '').trim();
    const projects = await getProjects(query);

    res.json({
      success: true,
      projects
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to fetch projects from Zoho Projects'
    });
  }
});

app.get('/api/zoho/projects/:projectId/users', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const users = await getProjectUsers(projectId);

    res.json({
      success: true,
      users
    });
  } catch (error) {
    const projectId = String(req.params.projectId || '').trim();
    res.status(500).json({
      success: false,
      message:
        error.message || `Failed to fetch Zoho project users for project ID: ${projectId || '(empty)'}`
    });
  }
});

app.get('/api/zoho/projects/:projectId/client-users', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const users = await getProjectClientUsers(projectId);

    res.json({
      success: true,
      users
    });
  } catch (error) {
    res.json({
      success: true,
      users: [],
      message: error.message || 'Zoho client users not available for this project.'
    });
  }
});

app.get('/api/zoho/projects/:projectId/tasks', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const tasks = await getProjectTasks(projectId, {
      query: String(req.query.query || '').trim(),
      status: String(req.query.status || '').trim(),
      index: req.query.index,
      range: req.query.range
    });

    res.json({
      success: true,
      tasks
    });
  } catch (error) {
    const projectId = String(req.params.projectId || '').trim();
    res.status(500).json({
      success: false,
      message:
        error.message || `Failed to fetch Zoho project tasks for project ID: ${projectId || '(empty)'}`
    });
  }
});

app.post('/api/mom/submit', async (req, res) => {
  try {
    const mom = sanitizeMomPayload(req.body.mom || {});
    const options = req.body.options || {};

    const validationErrors = validateMomPayload(mom);
    if (validationErrors.length) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: validationErrors
      });
    }

    const shouldGeneratePdf = Boolean(options.generatePdf || options.printPdf || options.sendEmail);

    if (!shouldGeneratePdf) {
      return res.status(400).json({
        success: false,
        message: 'Select at least one output option (Email, PDF, Print).'
      });
    }

    const authenticity = buildAuthenticityMetadata();
    const { fileName } = await generateMomPdf(mom, config.app.generatedDir, authenticity);
    const pdfUrl = `/generated-pdfs/${fileName}`;

    let emailDraft = null;
    if (options.sendEmail) {
      emailDraft = buildOutlookDraft({
        mom,
        options,
        pdfUrl
      });
    }

    return res.json({
      success: true,
      message: 'M.O.M processed successfully.',
      result: {
        pdfUrl,
        pdfFileName: fileName,
        pdfAbsoluteUrl: buildAbsolutePdfUrl(pdfUrl),
        authenticity,
        emailSent: false,
        emailDraft,
        printRequested: Boolean(options.printPdf)
      }
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to process M.O.M submission'
    });
  }
});

app.get('*', (_req, res) => {
  res.sendFile(path.join(config.app.rootDir, 'public', 'index.html'));
});

const server = app.listen(config.app.port, config.app.host, () => {
  // eslint-disable-next-line no-console
  console.log(`M.O.M app running at ${config.app.baseUrl} on port ${config.app.port}`);
});

server.on('error', (error) => {
  // eslint-disable-next-line no-console
  console.error(`Server startup failed: ${error.code || error.message}`);
  process.exit(1);
});
